FQBN=esp32:esp32:esp32:PSRAM=disabled,PartitionScheme=default,CPUFreq=240,FlashMode=qio,FlashFreq=80,FlashSize=4M,UploadSpeed=921600,DebugLevel=none

CC=arduino-cli


build: 
	$(CC) compile -b $(FQBN)  --warnings all


